/* Data comes from itinerary.js; regenerate it using node build.mjs. */
(function(){
'use strict';
const $=id=>document.getElementById(id),data=window.KYUSHU_DATA;
if(!data){$('updated').textContent='行程資料載入失敗，請重新整理或開啟文字版。';return;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function link(x){const raw=x.url||'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(x.query||x.label);const url=new URL(raw);if(url.protocol!=='https:')throw Error('Map URL must be HTTPS');return '<a href="'+esc(url.href)+'" target="_blank" rel="noopener noreferrer">'+esc(x.label||x.name)+'</a>';}
function city(d){const n=Number(d.date.slice(-2));return n===7?'福岡 → 熊本':n===10?'熊本 → 福岡':n===14?'福岡 → 桃園':d.city;}
function eventHTML(e){return '<div class="event"><span class="time">'+esc(e.time)+'</span><b>'+esc(e.title)+'</b>'+(e.places.length?'<div class="places">'+e.places.map(link).join(' · ')+'</div>':'')+(e.status?'<span class="badge">'+esc(e.status)+'</span>':'')+(e.note?'<span class="note">'+esc(e.note)+'</span>':'')+'</div>';}
function hotelHTML(h){return '<span class="hotelname">'+link({label:h.name,query:h.query})+'</span>'+h.start.slice(5).replace('-','/')+' 入住 → '+h.end.slice(5).replace('-','/')+' 退房 · '+h.nights+' 晚<span class="note">'+esc(h.note)+'</span>';}
let selected=0,forced=false,widths=data.days.map(()=>220);
let pref={};try{pref=JSON.parse(localStorage.getItem('kyushu-display')||'{}');}catch(_){}
if(pref.dark)document.documentElement.classList.add('dark');
if(Number.isFinite(pref.font)&&pref.font>=12&&pref.font<=24)$('font').value=pref.font;
function savePrefs(){try{localStorage.setItem('kyushu-display',JSON.stringify({dark:document.documentElement.classList.contains('dark'),font:Number($('font').value)}));}catch(_){}}
$('updated').textContent='行程更新：'+data.updatedAt+' · '+data.sourceVersion;
$('date').innerHTML=data.days.map((d,i)=>'<option value="'+i+'">'+d.date.slice(5).replace('-','/')+'（'+d.weekday+'）</option>').join('');
$('tabs').innerHTML=data.days.map((d,i)=>'<button class="tab" data-i="'+i+'">'+d.date.slice(5).replace('-','/')+'<small>週'+d.weekday+'</small></button>').join('');
function renderDay(){const d=data.days[selected];$('date').value=selected;$('city').textContent=city(d);$('count').textContent='第 '+(selected+1)+' / '+data.days.length+' 天 · '+d.people;document.querySelectorAll('.tab').forEach((t,i)=>{t.classList.toggle('active',i===selected);t.setAttribute('aria-pressed',i===selected?'true':'false');});$('prev').disabled=$('prevbottom').disabled=selected===0;$('next').disabled=$('nextbottom').disabled=selected===data.days.length-1;
let html=d.events.map(e=>'<article class="card '+esc(e.kind)+'">'+eventHTML(e)+'</article>').join('');if(!html)html='<article class="card"><span class="time">全天</span><h3>行程待排</h3><span class="note">尚未安排景點、餐廳或小鋼珠時段。</span></article>';const h=data.hotels.find(h=>d.date>=h.start&&d.date<h.end);html+=h?'<article class="card stay"><div class="staylabel">當晚住宿 · 已訂妥付款</div>'+hotelHTML(h)+'</article>':'<article class="card"><div class="staylabel">當晚住宿</div><h3>已返臺，無日本住宿</h3></article>';$('cards').innerHTML=html;}
function select(i,top){selected=Math.max(0,Math.min(data.days.length-1,i));renderDay();const t=$('tabs').children[selected];$('tabs').scrollTo({left:Math.max(0,t.offsetLeft-$('tabs').offsetLeft-$('tabs').clientWidth/2+t.offsetWidth/2),behavior:'smooth'});if(top)window.scrollTo({top:0,behavior:'smooth'});}
$('date').onchange=()=>select(Number($('date').value));$('tabs').onclick=e=>{const t=e.target.closest('button[data-i]');if(t)select(Number(t.dataset.i));};$('prev').onclick=()=>select(selected-1);$('next').onclick=()=>select(selected+1);$('prevbottom').onclick=()=>select(selected-1,true);$('nextbottom').onclick=()=>select(selected+1,true);
const slots=['06:00–08:00','08:00–10:00','10:00–12:00','12:00–14:00','14:00–16:00','16:00–18:00','18:00–20:00','20:00–22:00'];
$('cols').innerHTML='<col style="width:96px">'+data.days.map(()=>'<col>').join('');$('thead').innerHTML='<tr><th scope="col">時段</th>'+data.days.map((d,i)=>'<th scope="col"><span class="datehead">'+d.date.slice(5).replace('-','/')+'（'+d.weekday+'）</span><span class="cityhead">'+esc(city(d))+'</span><span class="people">'+esc(d.people)+'</span><span class="grip" tabindex="0" role="separator" aria-orientation="vertical" aria-label="調整'+d.date+'欄寬" data-i="'+i+'"></span></th>').join('')+'</tr>';
let rows='';for(let r=0;r<8;r++){rows+='<tr class="slot"><th class="rowhead" scope="row">'+slots[r]+'</th>';data.days.forEach(d=>{if(d.events.some(e=>e.slot<r&&e.slot+e.span>r))return;const ev=d.events.filter(e=>e.slot===r);rows+='<td rowspan="'+(ev[0]?.span||1)+'" class="'+esc(ev[0]?.kind||'')+'">'+(ev.length?ev.map(eventHTML).join(''):'<span class="empty">'+(r===0?'—':r===7&&d.date!=='2026-11-14'?'自由活動／休息（待排）':'待排')+'</span>')+'</td>';});rows+='</tr>';}
rows+='<tr><th class="rowhead" scope="row">住宿<small>當晚住宿</small></th>';for(let i=0;i<data.days.length;){const d=data.days[i],h=data.hotels.find(h=>d.date>=h.start&&d.date<h.end);if(!h){rows+='<td class="empty">返臺<br>無日本住宿</td>';i++;continue;}let span=1;while(i+span<data.days.length&&data.days[i+span].date<h.end)span++;rows+='<td colspan="'+span+'" class="stay">'+hotelHTML(h)+'</td>';i+=span;}rows+='</tr>';$('tbody').innerHTML=rows;
function applyWidths(){Array.from($('cols').children).slice(1).forEach((c,i)=>c.style.width=widths[i]+'px');$('table').style.width=(96+widths.reduce((a,b)=>a+b,0))+'px';document.querySelectorAll('.grip').forEach((g,i)=>{g.setAttribute('aria-valuemin','150');g.setAttribute('aria-valuemax','520');g.setAttribute('aria-valuenow',widths[i]);});}
document.querySelectorAll('.grip').forEach(g=>{const i=Number(g.dataset.i);g.onpointerdown=ev=>{ev.preventDefault();g.setPointerCapture(ev.pointerId);const start=ev.clientX,old=widths[i];const move=e=>{widths[i]=Math.max(150,Math.min(520,Math.round(old+e.clientX-start)));applyWidths();};const end=()=>{g.removeEventListener('pointermove',move);g.removeEventListener('pointerup',end);g.removeEventListener('pointercancel',end);};g.addEventListener('pointermove',move);g.addEventListener('pointerup',end);g.addEventListener('pointercancel',end);};g.onkeydown=ev=>{if(!['ArrowLeft','ArrowRight'].includes(ev.key))return;ev.preventDefault();widths[i]=Math.max(150,Math.min(520,widths[i]+(ev.key==='ArrowRight'?10:-10)));applyWidths();};});
$('font').oninput=()=>{document.documentElement.style.setProperty('--font',$('font').value+'px');$('fontout').textContent=$('font').value+' px';savePrefs();};$('width').oninput=()=>{widths.fill(Number($('width').value));$('widthout').textContent=$('width').value+' px';applyWidths();};$('viewwidth').oninput=()=>{$('frame').style.width=$('viewwidth').value+'%';$('viewwidthout').textContent=$('viewwidth').value+'%';};$('height').oninput=()=>{$('frame').style.height=$('height').value+'px';$('heightout').textContent=$('height').value+' px';};$('reset').onclick=()=>{widths.fill(220);$('width').value=220;$('widthout').textContent='220 px';$('viewwidth').value=100;$('viewwidth').oninput();$('height').value=650;$('height').oninput();applyWidths();$('frame').scrollTo({top:0,left:0});};
function themeLabel(){$('theme').textContent=document.documentElement.classList.contains('dark')?'切換白底':'切換黑底';}$('theme').onclick=()=>{document.documentElement.classList.toggle('dark');themeLabel();savePrefs();};function setMode(day){document.body.classList.toggle('daymode',day);document.body.classList.toggle('tablemode',!day);$('mode').textContent=day?'切換完整表格':'切換單日卡片';}const mq=matchMedia('(max-width:760px)');setMode(mq.matches);$('mode').onclick=()=>{forced=true;setMode(!document.body.classList.contains('daymode'));};mq.addEventListener('change',()=>{if(!forced)setMode(mq.matches);});applyWidths();renderDay();$('font').oninput();themeLabel();
})();
