/* Data comes from itinerary.js; regenerate it using node build.mjs. */
(function(){
'use strict';
const $=id=>document.getElementById(id),data=window.KYUSHU_DATA;
if(!data){$('updated').textContent='行程資料載入失敗，請重新整理或開啟文字版。';return;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function placeIcon(x,e){
  const label=x.label||x.name||'',context=(e?.title||'')+' '+(e?.note||'');
  if(e?.kind==='book'||/午餐|晚餐|燒肉|炸豬排|天婦羅|勝烈亭|柳川屋|鶴八|馬桜|肉の山翔/.test(label))return '🍽️';
  if(/飯店|旅館|HOTELS|INN|花畑/.test(label))return '🏨';
  if(/計程車/.test(e?.title||''))return '🚕';
  if(/A1 |A12 |機場捷運|電停|市役所前/.test(label))return '🚊';
  if(/機場|空港|航廈/.test(label))return '✈️';
  if(/Bus|巴士|新幹線口|西口/.test(label))return '🚌';
  if(/駅|站/.test(label))return /新幹線/.test(context)?'🚄':'🚆';
  if(/神社|天滿宮/.test(label))return '⛩️';
  if(/溫泉|地獄/.test(label))return '♨️';
  if(/阿蘇|由布嶽/.test(label))return '🌋';
  if(/草千里/.test(label))return '🌿';
  if(/運河城/.test(label))return '🛍️';
  return '📍';
}
function link(x,e,icon){const raw=x.url||'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(x.query||x.label);const url=new URL(raw);if(url.protocol!=='https:')throw Error('Map URL must be HTTPS');return '<a href="'+esc(url.href)+'" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">'+(icon||placeIcon(x,e))+'</span> '+esc(x.label||x.name)+'</a>';}
function city(d){const n=Number(d.date.slice(-2));return n===7?'福岡 → 熊本':n===10?'熊本 → 福岡':n===14?'福岡 → 桃園':d.city;}
function eventHTML(e){const places=e.places.map((p,i)=>'<span class="place-item">'+link(p,e)+(e.kind==='move'&&i<e.places.length-1?'<span class="place-separator" aria-label="前往">→</span>':'')+'</span>').join(' ');return '<div class="event"><span class="time"><span aria-hidden="true">🕒 </span>'+esc(e.time)+'</span><b>'+esc(e.title)+'</b>'+(e.places.length?'<div class="places '+(e.kind==='move'?'route':'')+'">'+places+'</div>':'')+(e.status?'<span class="badge">'+esc(e.status)+'</span>':'')+(e.note?'<span class="note">'+esc(e.note)+'</span>':'')+'</div>';}
function hotelHTML(h){return '<span class="hotelname">'+link({label:h.name,query:h.query},null,'🏨')+'</span>'+h.start.slice(5).replace('-','/')+' 入住 → '+h.end.slice(5).replace('-','/')+' 退房 · '+h.nights+' 晚<span class="note">'+esc(h.note)+'</span>';}
let selected=0,forced=false,widths=data.days.map(()=>160),autoFit=true,locked=true,rowHeight=400,visibleDays=7,manualRows=false,manualViewport=false,startIndex=0,shownDays=[];
let tableFull=false,fullState=null;
let automaticDays=matchMedia('(max-width:1024px)').matches;
if(automaticDays){visibleDays=1;$('visibleDays').value='auto';}
$('settings').onclick=()=>{const open=document.body.classList.toggle('controlsopen');$('settings').setAttribute('aria-expanded',String(open));$('settings').innerHTML='顯示設定 <span aria-hidden="true">'+(open?'−':'＋')+'</span>';fitViewport();};
document.querySelector('.route-nav').onclick=e=>{const button=e.target.closest('button[data-route]');if(!button)return;const i=Number(button.dataset.route);if(document.body.classList.contains('daymode'))select(i);else{startIndex=i;$('startdate').value=i;autoFit=true;renderTable();fitViewport();$('frame').scrollTo({top:0,left:0});}document.getElementById('journey').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});};
function preventMobileZoom(e){if(matchMedia('(max-width:760px)').matches&&(e.type==='gesturestart'||e.touches?.length>1))e.preventDefault();}
document.addEventListener('gesturestart',preventMobileZoom,{passive:false});
document.addEventListener('touchmove',preventMobileZoom,{passive:false});
let pref={};try{pref=JSON.parse(localStorage.getItem('kyushu-display')||'{}')||{};}catch(_){}
document.documentElement.classList.toggle('dark',pref.dark!==false);
if(pref.layoutVersion===3&&Number.isFinite(pref.font)&&pref.font>=12&&pref.font<=24)$('font').value=pref.font;
function savePrefs(){try{localStorage.setItem('kyushu-display',JSON.stringify({dark:document.documentElement.classList.contains('dark'),font:Number($('font').value),layoutVersion:3}));}catch(_){}}
function routeState(i){const start=i>=7?7:i>=4?4:0;document.querySelectorAll('[data-route]').forEach(b=>{const active=Number(b.dataset.route)===start;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});}
$('updated').textContent='行程更新：'+data.updatedAt+' · '+data.sourceVersion;
$('date').innerHTML=data.days.map((d,i)=>'<option value="'+i+'">'+d.date.slice(5).replace('-','/')+'（'+d.weekday+'）</option>').join('');
$('tabs').innerHTML=data.days.map((d,i)=>'<button class="tab" data-i="'+i+'">'+d.date.slice(5).replace('-','/')+'<small>週'+d.weekday+'</small></button>').join('');
function renderDay(){routeState(selected);const d=data.days[selected];$('date').value=selected;$('city').textContent=city(d);$('count').textContent='第 '+(selected+1)+' / '+data.days.length+' 天 · '+d.people;document.querySelectorAll('.tab').forEach((t,i)=>{t.classList.toggle('active',i===selected);t.setAttribute('aria-pressed',i===selected?'true':'false');});$('prev').disabled=$('prevbottom').disabled=selected===0;$('next').disabled=$('nextbottom').disabled=selected===data.days.length-1;
let html=d.events.map(e=>'<article class="card '+esc(e.kind)+'">'+eventHTML(e)+'</article>').join('');if(!html)html='<article class="card"><span class="time">全天</span><h3>行程待排</h3><span class="note">尚未安排景點、餐廳或小鋼珠時段。</span></article>';const h=data.hotels.find(h=>d.date>=h.start&&d.date<h.end);html+=h?'<article class="card stay"><div class="staylabel">當晚住宿 · 已訂妥付款</div>'+hotelHTML(h)+'</article>':'<article class="card"><div class="staylabel">當晚住宿</div><h3>已返臺，無日本住宿</h3></article>';$('cards').innerHTML=html;}
function select(i,top){selected=Math.max(0,Math.min(data.days.length-1,i));renderDay();const t=$('tabs').children[selected];$('tabs').scrollTo({left:Math.max(0,t.offsetLeft-$('tabs').offsetLeft-$('tabs').clientWidth/2+t.offsetWidth/2),behavior:'smooth'});if(top)window.scrollTo({top:0,behavior:'smooth'});}
$('date').onchange=()=>select(Number($('date').value));$('tabs').onclick=e=>{const t=e.target.closest('button[data-i]');if(t)select(Number(t.dataset.i));};$('prev').onclick=()=>select(selected-1);$('next').onclick=()=>select(selected+1);$('prevbottom').onclick=()=>select(selected-1,true);$('nextbottom').onclick=()=>select(selected+1,true);
const slots=['06:00–08:00','08:00–10:00','10:00–12:00','12:00–14:00','14:00–16:00','16:00–18:00','18:00–20:00','20:00–22:00'];
let timeColumn=86;
$('startdate').innerHTML=data.days.map((d,i)=>'<option value="'+i+'">'+d.date.slice(5).replace('-','/')+'</option>').join('');
function renderTable(){
routeState(startIndex);
shownDays=data.days.slice(startIndex);while(shownDays.length<visibleDays)shownDays.push(null);widths=shownDays.map((_,i)=>widths[i]||160);
$('cols').innerHTML='<col style="width:'+timeColumn+'px">'+shownDays.map(()=>'<col>').join('');$('thead').innerHTML='<tr><th scope="col">時段</th>'+shownDays.map((d,i)=>d?'<th scope="col"><span class="datehead">'+d.date.slice(5).replace('-','/')+'（'+d.weekday+'）</span><span class="cityhead">'+esc(city(d))+'</span><span class="people">'+esc(d.people)+'</span><span class="grip" tabindex="-1" role="separator" aria-orientation="vertical" aria-label="調整'+d.date+'欄寬" data-i="'+i+'"></span></th>':'<th class="placeholder" aria-label="行程結束後留白"></th>').join('')+'</tr>';
let rows='';for(let r=0;r<8;r++){const times=slots[r].split('–');rows+='<tr class="slot"><th class="rowhead" scope="row"><span class="slot-time"><span>'+times[0]+'</span><span>～</span><span>'+times[1]+'</span></span><span class="rowgrip" tabindex="-1" role="separator" aria-orientation="horizontal" aria-label="同時調整全部時段列高"></span></th>';shownDays.forEach(d=>{if(!d){rows+='<td class="placeholder"></td>';return;}if(d.events.some(e=>e.slot<r&&e.slot+e.span>r))return;const ev=d.events.filter(e=>e.slot===r),span=ev[0]?.span||1;rows+='<td rowspan="'+span+'" class="'+esc(ev[0]?.kind||'')+'"><div class="cell-content" style="--span:'+span+'" tabindex="0" aria-label="'+esc(d.date+' '+slots[r]+'行程')+'">'+(ev.length?ev.map(eventHTML).join(''):'<span class="empty">'+(r===0?'—':r===7&&d.date!=='2026-11-14'?'自由活動／休息（待排）':'待排')+'</span>')+'</div></td>';});rows+='</tr>';}
rows+='<tr class="slot"><th class="rowhead" scope="row">住宿<small>當晚住宿</small><span class="rowgrip" tabindex="-1" role="separator" aria-orientation="horizontal" aria-label="同時調整全部時段列高"></span></th>';for(let i=0;i<shownDays.length;){const d=shownDays[i];if(!d){rows+='<td class="placeholder"></td>';i++;continue;}const h=data.hotels.find(h=>d.date>=h.start&&d.date<h.end);if(!h){rows+='<td class="empty"><div class="cell-content" style="--span:1" tabindex="0" aria-label="'+esc(d.date+'住宿')+'">返臺<br>無日本住宿</div></td>';i++;continue;}let span=1;while(shownDays[i+span]&&shownDays[i+span].date<h.end)span++;rows+='<td colspan="'+span+'" class="stay"><div class="cell-content" style="--span:1" tabindex="0" aria-label="'+esc(h.name+'住宿')+'">'+hotelHTML(h)+'</div></td>';i+=span;}rows+='</tr>';$('tbody').innerHTML=rows;
installTableResizers();applyRows();updateLock();fitDays();syncScroll();
}
function applyFont(){const size=Number($('font').value);document.documentElement.style.setProperty('--font',size+'px');}
function minimumWidth(){return Math.max(1,($('frame').clientWidth-timeColumn-1)/data.days.length);}
function maximumWidth(){return Math.max(520,($('frame').clientWidth-timeColumn-1)/4);}
function applyWidths(){const min=minimumWidth(),max=maximumWidth();widths=widths.map(w=>Math.max(min,Math.min(max,w)));Array.from($('cols').children).slice(1).forEach((c,i)=>c.style.width=widths[i]+'px');$('table').style.width=(timeColumn+widths.reduce((a,b)=>a+b,0))+'px';document.querySelectorAll('.grip').forEach((g,i)=>{g.setAttribute('aria-valuemin',min.toFixed(4));g.setAttribute('aria-valuemax',max.toFixed(4));g.setAttribute('aria-valuenow',widths[i].toFixed(4));});$('width').min=min;$('width').max=max;$('width').value=widths[0];}
function fitDays(){if(!$('frame').clientWidth)return;timeColumn=matchMedia('(max-width:760px)').matches?64:86;$('cols').firstElementChild.style.width=timeColumn+'px';if(automaticDays){const days=matchMedia('(max-width:1024px)').matches?Math.max(1,Math.floor(($('frame').clientWidth-timeColumn-1)/260)):7;if(days!==visibleDays){visibleDays=days;if(shownDays.length<visibleDays){renderTable();return;}}}if(autoFit)widths.fill(($('frame').clientWidth-timeColumn-1)/visibleDays);applyWidths();}
function applyRows(){document.body.classList.toggle('autorows',locked||!manualRows);document.documentElement.style.setProperty('--row-height',rowHeight+'px');$('rowheight').value=rowHeight;document.querySelectorAll('.rowgrip').forEach(g=>{g.setAttribute('aria-valuemin','100');g.setAttribute('aria-valuemax','600');g.setAttribute('aria-valuenow',rowHeight);});}
function maximumFrameHeight(){return Math.ceil($('table').getBoundingClientRect().height+20);}
function setFrameHeight(height){const max=maximumFrameHeight();height=Math.max(100,Math.min(max,height));$('frame').style.height=height+'px';$('height').max=Math.max(100,max);$('height').value=height;$('framegrip').setAttribute('aria-valuemin','100');$('framegrip').setAttribute('aria-valuemax',max);$('framegrip').setAttribute('aria-valuenow',height);}
function fitViewport(){if(tableFull){document.documentElement.style.setProperty('--full-toolbar-bottom',Math.ceil(document.querySelector('.toolbar').getBoundingClientRect().bottom+8)+'px');return;}if(!$('frame').clientWidth)return;if(manualViewport){setFrameHeight($('frame').getBoundingClientRect().height);return;}const viewport=window.visualViewport?.height||window.innerHeight,top=$('frame').getBoundingClientRect().top+window.scrollY;setFrameHeight(2*Math.max(100,Math.floor(viewport-top-56)));}
function syncScroll(){const frame=$('frame');for(const vertical of [false,true]){const track=$(vertical?'vscroll':'hscroll'),thumb=$(vertical?'vthumb':'hthumb'),size=vertical?'Height':'Width',pos=vertical?'Top':'Left',max=Math.max(0,frame['scroll'+size]-frame['client'+size]),length=track['client'+size],extent=Math.min(length,Math.max(36,length*frame['client'+size]/Math.max(1,frame['scroll'+size])));thumb.style[size.toLowerCase()]=extent+'px';thumb.style[pos.toLowerCase()]=(max?frame['scroll'+pos]/max*(length-extent):0)+'px';track.setAttribute('aria-valuemin','0');track.setAttribute('aria-valuemax',max);track.setAttribute('aria-valuenow',Math.round(frame['scroll'+pos]));track.setAttribute('aria-disabled',String(!max));}}
function updateLock(){document.body.classList.toggle('sizeslocked',locked);$('lock').textContent=locked?'🔒 尺寸已鎖定':'🔓 尺寸可調整';$('lock').setAttribute('aria-pressed',String(locked));$('lock').setAttribute('aria-label',locked?'解除欄寬與列高鎖定':'鎖定欄寬與列高');$('width').disabled=$('rowheight').disabled=locked;document.querySelectorAll('.grip,.rowgrip').forEach(g=>{g.tabIndex=locked?-1:0;g.setAttribute('aria-disabled',String(locked));});}
function attachResize(g,axis,getValue,setValue,min,max){const clamp=v=>Math.max(min(),Math.min(max(),v));g.onpointerdown=ev=>{if(locked||ev.button!==0)return;ev.preventDefault();g.setPointerCapture(ev.pointerId);const start=ev[axis],old=getValue();const move=e=>{if(!locked)setValue(clamp(Math.round(old+e[axis]-start)));};const end=()=>{g.removeEventListener('pointermove',move);g.removeEventListener('pointerup',end);g.removeEventListener('pointercancel',end);g.removeEventListener('lostpointercapture',end);};g.addEventListener('pointermove',move);g.addEventListener('pointerup',end);g.addEventListener('pointercancel',end);g.addEventListener('lostpointercapture',end);};g.onkeydown=ev=>{if(locked)return;const negative=axis==='clientX'?'ArrowLeft':'ArrowUp',positive=axis==='clientX'?'ArrowRight':'ArrowDown';if(![negative,positive].includes(ev.key))return;ev.preventDefault();setValue(clamp(getValue()+(ev.key===positive?10:-10)));};}
function installTableResizers(){document.querySelectorAll('.grip').forEach(g=>{const i=Number(g.dataset.i);attachResize(g,'clientX',()=>widths[i],v=>{autoFit=false;widths[i]=v;applyWidths();},minimumWidth,maximumWidth);});
document.querySelectorAll('.rowgrip').forEach(g=>attachResize(g,'clientY',()=>rowHeight,v=>{manualRows=true;rowHeight=v;applyRows();},()=>100,()=>600));
}
$('frame').addEventListener('scroll',syncScroll,{passive:true});
$('hscroll').onkeydown=e=>{const f=$('frame');if(!['ArrowLeft','ArrowRight','PageUp','PageDown','Home','End'].includes(e.key))return;e.preventDefault();if(e.key==='Home')f.scrollLeft=0;else if(e.key==='End')f.scrollLeft=f.scrollWidth;else f.scrollLeft+=(e.key==='ArrowLeft'?-60:e.key==='ArrowRight'?60:e.key==='PageUp'?-f.clientWidth:f.clientWidth);syncScroll();};
$('hscroll').onpointerdown=e=>{if(e.target===$('hthumb'))return;const f=$('frame');f.scrollLeft+=(e.clientX<$('hthumb').getBoundingClientRect().left?-f.clientWidth:f.clientWidth);syncScroll();};
$('vscroll').onkeydown=e=>{const f=$('frame');if(!['ArrowUp','ArrowDown','PageUp','PageDown','Home','End'].includes(e.key))return;e.preventDefault();if(e.key==='Home')f.scrollTop=0;else if(e.key==='End')f.scrollTop=f.scrollHeight;else f.scrollTop+=(e.key==='ArrowUp'?-60:e.key==='ArrowDown'?60:e.key==='PageUp'?-f.clientHeight:f.clientHeight);syncScroll();};
$('vscroll').onpointerdown=e=>{if(e.button!==0||e.target===$('vthumb'))return;const f=$('frame');f.scrollTop+=(e.clientY<$('vthumb').getBoundingClientRect().top?-f.clientHeight:f.clientHeight);syncScroll();};
function pointerDrag(handle,axis,move){handle.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();handle.setPointerCapture(e.pointerId);const apply=move(e);const update=ev=>apply(ev);const end=()=>{handle.removeEventListener('pointermove',update);handle.removeEventListener('pointerup',end);handle.removeEventListener('pointercancel',end);handle.removeEventListener('lostpointercapture',end);};handle.addEventListener('pointermove',update);handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);handle.addEventListener('lostpointercapture',end);};}
pointerDrag($('hthumb'),'clientX',e=>{const x=e.clientX,left=$('frame').scrollLeft,max=$('frame').scrollWidth-$('frame').clientWidth,travel=$('hscroll').clientWidth-$('hthumb').getBoundingClientRect().width;return ev=>{if(travel>0)$('frame').scrollLeft=left+(ev.clientX-x)*max/travel;syncScroll();};});
pointerDrag($('vthumb'),'clientY',e=>{const y=e.clientY,top=$('frame').scrollTop,max=$('frame').scrollHeight-$('frame').clientHeight,travel=$('vscroll').clientHeight-$('vthumb').getBoundingClientRect().height;return ev=>{if(travel>0)$('frame').scrollTop=top+(ev.clientY-y)*max/travel;syncScroll();};});
pointerDrag($('framegrip'),'clientY',e=>{const y=e.clientY,height=$('frame').getBoundingClientRect().height;return ev=>{manualViewport=true;setFrameHeight(Math.round(height+ev.clientY-y));};});
$('framegrip').onkeydown=e=>{if(!['ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();manualViewport=true;setFrameHeight(e.key==='Home'?100:e.key==='End'?maximumFrameHeight():$('frame').getBoundingClientRect().height+(e.key==='ArrowDown'?30:-30));};
$('lock').onclick=()=>{locked=!locked;manualRows=false;updateLock();applyRows();};
$('font').oninput=()=>{applyFont();savePrefs();};$('width').oninput=()=>{if(locked)return;autoFit=false;widths.fill(Number($('width').value));applyWidths();};$('rowheight').oninput=()=>{if(locked)return;manualRows=true;rowHeight=Number($('rowheight').value);applyRows();};$('height').oninput=()=>{manualViewport=true;setFrameHeight(Number($('height').value));};$('visibleDays').onchange=()=>{automaticDays=$('visibleDays').value==='auto';visibleDays=automaticDays?1:Number($('visibleDays').value);autoFit=true;renderTable();$('frame').scrollTo({left:0});};$('startdate').onchange=()=>{startIndex=Number($('startdate').value);autoFit=true;renderTable();fitViewport();$('frame').scrollTo({top:0,left:0});};$('reset').onclick=()=>{autoFit=true;manualRows=false;manualViewport=false;rowHeight=400;automaticDays=matchMedia('(max-width:1024px)').matches;visibleDays=automaticDays?1:7;startIndex=0;$('startdate').value=0;$('visibleDays').value=automaticDays?'auto':'7';$('font').value=16;applyFont();savePrefs();renderTable();fitViewport();$('frame').scrollTo({top:0,left:0});};
renderTable();
function toggleTableFull(){const f=$('frame');if(!tableFull){fullState={day:document.body.classList.contains('daymode'),forced,manualViewport,height:f.style.height,pageY:window.scrollY,left:f.scrollLeft,top:f.scrollTop};tableFull=true;document.body.classList.add('tablefull');setMode(false);}else{tableFull=false;document.body.classList.remove('tablefull');manualViewport=fullState.manualViewport;f.style.height=fullState.height;forced=fullState.forced;setMode(fullState.day);f.scrollTo({left:fullState.left,top:fullState.top});window.scrollTo({top:fullState.pageY});}const label=tableFull?'恢復原畫面':'表格全螢幕';$('fullscreen').setAttribute('aria-label',label);$('fullscreen').title=label;$('fullscreen').setAttribute('aria-pressed',String(tableFull));$('fullscreen').querySelector('path').setAttribute('d',tableFull?'M3 3l6 6M4 9h5V4M21 3l-6 6M15 4v5h5M3 21l6-6M4 15h5v5M21 21l-6-6M15 20v-5h5':'M9 9 3 3M3 8V3h5M15 9l6-6M16 3h5v5M9 15l-6 6M3 16v5h5M15 15l6 6M16 21h5v-5');syncScroll();}
$('fullscreen').onclick=toggleTableFull;document.addEventListener('keydown',e=>{if(tableFull&&e.key==='Escape'){e.preventDefault();toggleTableFull();}});
function themeLabel(){const dark=document.documentElement.classList.contains('dark'),label=dark?'切換白底':'切換黑底';$('theme').textContent=dark?'☀️':'🌙';$('theme').setAttribute('aria-label',label);$('theme').title=label;document.querySelector('meta[name="theme-color"]').content=dark?'#101613':'#f4f2eb';}$('theme').onclick=()=>{document.documentElement.classList.toggle('dark');themeLabel();savePrefs();};function setMode(day){document.body.classList.toggle('daymode',day);document.body.classList.toggle('tablemode',!day);$('mode').textContent=day?'切換完整表格':'切換單日卡片';fitDays();applyFont();fitViewport();}const mq=matchMedia('(max-width:1024px)');setMode(mq.matches);$('mode').onclick=()=>{forced=true;setMode(!document.body.classList.contains('daymode'));};mq.addEventListener('change',()=>{if(!forced&&!tableFull)setMode(mq.matches);});new ResizeObserver(()=>{fitDays();syncScroll();fitViewport();}).observe($('frame'));new ResizeObserver(()=>{syncScroll();fitViewport();}).observe(document.getElementById('table'));const layoutObserver=new ResizeObserver(fitViewport);layoutObserver.observe(document.querySelector('.toolbar'));layoutObserver.observe($('sizehint'));window.addEventListener('resize',fitViewport);window.visualViewport?.addEventListener('resize',fitViewport);applyWidths();applyRows();updateLock();renderDay();themeLabel();
})();
