/* Data comes from itinerary.js; regenerate it using node build.mjs. */
(function(){
'use strict';
const $=id=>document.getElementById(id),data=window.KYUSHU_DATA;
if(!data){$('updated').textContent='行程資料載入失敗，請重新整理或開啟文字版。';return;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function placeIcon(x,e){
  const label=x.label||x.name||'',context=(e?.title||'')+' '+(e?.note||'');
  if(e?.kind==='book'||/午餐|晚餐|燒肉|炸豬排|天婦羅|勝烈亭|柳川屋|鶴八|馬桜|肉の山翔/.test(label))return '🍽️';
  if(/飯店|旅館|HOTELS|INN|花畑/.test(label))return '🏨';
  if(/計程車/.test(e?.title||''))return '🚕';
  if(/A1 |A12 |機場捷運|電停|市役所前/.test(label))return '🚊';
  if(/機場|空港|航廈/.test(label))return '✈️';
  if(/Bus|巴士|新幹線口|西口/.test(label))return '🚌';
  if(/駅|站/.test(label))return /新幹線/.test(context)?'🚄':'🚆';
  if(/神社|天滿宮/.test(label))return '⛩️';
  if(/溫泉|地獄/.test(label))return '♨️';
  if(/阿蘇|由布嶽/.test(label))return '🌋';
  if(/草千里/.test(label))return '🌿';
  if(/運河城/.test(label))return '🛍️';
  return '📍';
}
function link(x,e,icon){const raw=x.url||'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(x.query||x.label);const url=new URL(raw);if(url.protocol!=='https:')throw Error('Map URL must be HTTPS');return '<a href="'+esc(url.href)+'" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">'+(icon||placeIcon(x,e))+'</span> '+esc(x.label||x.name)+'</a>';}
function city(d){const n=Number(d.date.slice(-2));return n===7?'福岡 → 熊本':n===10?'熊本 → 福岡':n===14?'福岡 → 桃園':d.city;}
function eventHTML(e){return '<div class="event"><span class="time"><span aria-hidden="true">🕒 </span>'+esc(e.time)+'</span><b>'+esc(e.title)+'</b>'+(e.places.length?'<div class="places">'+e.places.map(p=>link(p,e)).join(' · ')+'</div>':'')+(e.status?'<span class="badge">'+esc(e.status)+'</span>':'')+(e.note?'<span class="note">'+esc(e.note)+'</span>':'')+'</div>';}
function hotelHTML(h){return '<span class="hotelname">'+link({label:h.name,query:h.query},null,'🏨')+'</span>'+h.start.slice(5).replace('-','/')+' 入住 → '+h.end.slice(5).replace('-','/')+' 退房 · '+h.nights+' 晚<span class="note">'+esc(h.note)+'</span>';}
let selected=0,forced=false,widths=data.days.map(()=>110),autoFit=true,locked=true,rowHeight=180;
let pref={};try{pref=JSON.parse(localStorage.getItem('kyushu-display')||'{}');}catch(_){}
document.documentElement.classList.toggle('dark',pref.dark!==false);
if(Number.isFinite(pref.font)&&pref.font>=12&&pref.font<=24)$('font').value=pref.font;
let manualFont=Number.isFinite(pref.font)&&pref.font>=12&&pref.font<=24;
function savePrefs(){try{localStorage.setItem('kyushu-display',JSON.stringify({dark:document.documentElement.classList.contains('dark'),...(manualFont?{font:Number($('font').value)}:{})}));}catch(_){}}
$('updated').textContent='行程更新：'+data.updatedAt+' · '+data.sourceVersion;
$('date').innerHTML=data.days.map((d,i)=>'<option value="'+i+'">'+d.date.slice(5).replace('-','/')+'（'+d.weekday+'）</option>').join('');
$('tabs').innerHTML=data.days.map((d,i)=>'<button class="tab" data-i="'+i+'">'+d.date.slice(5).replace('-','/')+'<small>週'+d.weekday+'</small></button>').join('');
function renderDay(){const d=data.days[selected];$('date').value=selected;$('city').textContent=city(d);$('count').textContent='第 '+(selected+1)+' / '+data.days.length+' 天 · '+d.people;document.querySelectorAll('.tab').forEach((t,i)=>{t.classList.toggle('active',i===selected);t.setAttribute('aria-pressed',i===selected?'true':'false');});$('prev').disabled=$('prevbottom').disabled=selected===0;$('next').disabled=$('nextbottom').disabled=selected===data.days.length-1;
let html=d.events.map(e=>'<article class="card '+esc(e.kind)+'">'+eventHTML(e)+'</article>').join('');if(!html)html='<article class="card"><span class="time">全天</span><h3>行程待排</h3><span class="note">尚未安排景點、餐廳或小鋼珠時段。</span></article>';const h=data.hotels.find(h=>d.date>=h.start&&d.date<h.end);html+=h?'<article class="card stay"><div class="staylabel">當晚住宿 · 已訂妥付款</div>'+hotelHTML(h)+'</article>':'<article class="card"><div class="staylabel">當晚住宿</div><h3>已返臺，無日本住宿</h3></article>';$('cards').innerHTML=html;}
function select(i,top){selected=Math.max(0,Math.min(data.days.length-1,i));renderDay();const t=$('tabs').children[selected];$('tabs').scrollTo({left:Math.max(0,t.offsetLeft-$('tabs').offsetLeft-$('tabs').clientWidth/2+t.offsetWidth/2),behavior:'smooth'});if(top)window.scrollTo({top:0,behavior:'smooth'});}
$('date').onchange=()=>select(Number($('date').value));$('tabs').onclick=e=>{const t=e.target.closest('button[data-i]');if(t)select(Number(t.dataset.i));};$('prev').onclick=()=>select(selected-1);$('next').onclick=()=>select(selected+1);$('prevbottom').onclick=()=>select(selected-1,true);$('nextbottom').onclick=()=>select(selected+1,true);
const slots=['06:00–08:00','08:00–10:00','10:00–12:00','12:00–14:00','14:00–16:00','16:00–18:00','18:00–20:00','20:00–22:00'];
const timeColumn=86;
$('cols').innerHTML='<col style="width:'+timeColumn+'px">'+data.days.map(()=>'<col>').join('');$('thead').innerHTML='<tr><th scope="col">時段</th>'+data.days.map((d,i)=>'<th scope="col"><span class="datehead">'+d.date.slice(5).replace('-','/')+'（'+d.weekday+'）</span><span class="cityhead">'+esc(city(d))+'</span><span class="people">'+esc(d.people)+'</span><span class="grip" tabindex="-1" role="separator" aria-orientation="vertical" aria-label="調整'+d.date+'欄寬" data-i="'+i+'"></span></th>').join('')+'</tr>';
let rows='';for(let r=0;r<8;r++){rows+='<tr class="slot"><th class="rowhead" scope="row">'+slots[r]+'<span class="rowgrip" tabindex="-1" role="separator" aria-orientation="horizontal" aria-label="同時調整全部時段列高"></span></th>';data.days.forEach(d=>{if(d.events.some(e=>e.slot<r&&e.slot+e.span>r))return;const ev=d.events.filter(e=>e.slot===r),span=ev[0]?.span||1;rows+='<td rowspan="'+span+'" class="'+esc(ev[0]?.kind||'')+'"><div class="cell-content" style="--span:'+span+'" tabindex="0" aria-label="'+esc(d.date+' '+slots[r]+'行程')+'">'+(ev.length?ev.map(eventHTML).join(''):'<span class="empty">'+(r===0?'—':r===7&&d.date!=='2026-11-14'?'自由活動／休息（待排）':'待排')+'</span>')+'</div></td>';});rows+='</tr>';}
rows+='<tr class="slot"><th class="rowhead" scope="row">住宿<small>當晚住宿</small><span class="rowgrip" tabindex="-1" role="separator" aria-orientation="horizontal" aria-label="同時調整全部時段列高"></span></th>';for(let i=0;i<data.days.length;){const d=data.days[i],h=data.hotels.find(h=>d.date>=h.start&&d.date<h.end);if(!h){rows+='<td class="empty"><div class="cell-content" style="--span:1" tabindex="0" aria-label="'+esc(d.date+'住宿')+'">返臺<br>無日本住宿</div></td>';i++;continue;}let span=1;while(i+span<data.days.length&&data.days[i+span].date<h.end)span++;rows+='<td colspan="'+span+'" class="stay"><div class="cell-content" style="--span:1" tabindex="0" aria-label="'+esc(h.name+'住宿')+'">'+hotelHTML(h)+'</div></td>';i+=span;}rows+='</tr>';$('tbody').innerHTML=rows;
function applyFont(){const size=manualFont?Number($('font').value):document.body.classList.contains('daymode')?16:Math.max(13,Math.min(16,Math.round(widths.reduce((a,b)=>a+b,0)/widths.length/8)));$('font').value=size;$('fontout').textContent=size+' px';document.documentElement.style.setProperty('--font',size+'px');}
function applyWidths(){Array.from($('cols').children).slice(1).forEach((c,i)=>c.style.width=widths[i]+'px');$('table').style.width=(timeColumn+widths.reduce((a,b)=>a+b,0))+'px';document.querySelectorAll('.grip').forEach((g,i)=>{g.setAttribute('aria-valuemin','56');g.setAttribute('aria-valuemax','520');g.setAttribute('aria-valuenow',Math.round(widths[i]));});const uniform=widths.every(w=>w===widths[0]);$('width').value=Math.round(widths[0]);$('widthout').textContent=uniform?Math.round(widths[0])+' px':'個別';applyFont();}
function fitDays(){if(!autoFit||!$('frame').clientWidth)return;widths.fill(Math.max(56,($('frame').clientWidth-timeColumn-1)/data.days.length));applyWidths();}
function applyRows(){document.documentElement.style.setProperty('--row-height',rowHeight+'px');$('rowheight').value=rowHeight;$('rowheightout').textContent=rowHeight+' px';document.querySelectorAll('.rowgrip').forEach(g=>{g.setAttribute('aria-valuemin','100');g.setAttribute('aria-valuemax','400');g.setAttribute('aria-valuenow',rowHeight);});}
function updateLock(){document.body.classList.toggle('sizeslocked',locked);$('lock').textContent=locked?'🔒 尺寸已鎖定':'🔓 尺寸可調整';$('lock').setAttribute('aria-pressed',String(locked));$('lock').setAttribute('aria-label',locked?'解除欄寬與列高鎖定':'鎖定欄寬與列高');$('width').disabled=$('rowheight').disabled=locked;document.querySelectorAll('.grip,.rowgrip').forEach(g=>{g.tabIndex=locked?-1:0;g.setAttribute('aria-disabled',String(locked));});}
function attachResize(g,axis,getValue,setValue,min,max){g.onpointerdown=ev=>{if(locked||ev.button!==0)return;ev.preventDefault();g.setPointerCapture(ev.pointerId);const start=ev[axis],old=getValue();const move=e=>{if(!locked)setValue(Math.max(min,Math.min(max,Math.round(old+e[axis]-start))));};const end=()=>{g.removeEventListener('pointermove',move);g.removeEventListener('pointerup',end);g.removeEventListener('pointercancel',end);g.removeEventListener('lostpointercapture',end);};g.addEventListener('pointermove',move);g.addEventListener('pointerup',end);g.addEventListener('pointercancel',end);g.addEventListener('lostpointercapture',end);};g.onkeydown=ev=>{if(locked)return;const negative=axis==='clientX'?'ArrowLeft':'ArrowUp',positive=axis==='clientX'?'ArrowRight':'ArrowDown';if(![negative,positive].includes(ev.key))return;ev.preventDefault();setValue(Math.max(min,Math.min(max,getValue()+(ev.key===positive?10:-10))));};}
document.querySelectorAll('.grip').forEach(g=>{const i=Number(g.dataset.i);attachResize(g,'clientX',()=>widths[i],v=>{autoFit=false;widths[i]=v;applyWidths();},56,520);});
document.querySelectorAll('.rowgrip').forEach(g=>attachResize(g,'clientY',()=>rowHeight,v=>{rowHeight=v;applyRows();},100,400));
$('lock').onclick=()=>{locked=!locked;updateLock();};
$('font').oninput=()=>{manualFont=true;applyFont();savePrefs();};$('width').oninput=()=>{if(locked)return;autoFit=false;widths.fill(Number($('width').value));applyWidths();};$('rowheight').oninput=()=>{if(locked)return;rowHeight=Number($('rowheight').value);applyRows();};$('height').oninput=()=>{$('frame').style.height=$('height').value+'px';$('heightout').textContent=$('height').value+' px';};$('reset').onclick=()=>{autoFit=true;rowHeight=180;applyRows();$('height').value=650;$('height').oninput();fitDays();$('frame').scrollTo({top:0,left:0});};
function themeLabel(){const dark=document.documentElement.classList.contains('dark'),label=dark?'切換白底':'切換黑底';$('theme').textContent=dark?'☀️':'🌙';$('theme').setAttribute('aria-label',label);$('theme').title=label;}$('theme').onclick=()=>{document.documentElement.classList.toggle('dark');themeLabel();savePrefs();};function setMode(day){document.body.classList.toggle('daymode',day);document.body.classList.toggle('tablemode',!day);$('mode').textContent=day?'切換完整表格':'切換單日卡片';fitDays();applyFont();}const mq=matchMedia('(max-width:760px)');setMode(mq.matches);$('mode').onclick=()=>{forced=true;setMode(!document.body.classList.contains('daymode'));};mq.addEventListener('change',()=>{if(!forced)setMode(mq.matches);});new ResizeObserver(fitDays).observe($('frame'));applyWidths();applyRows();updateLock();renderDay();themeLabel();
})();
